{{- if eq .Values.global.db.internal true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.db.secret.data.dbhost }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName}}
spec:
  selector:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
    - name: {{ .Values.appName }}
      protocol: TCP
      port: 5432
      targetPort: 5432
  {{- end }}
