component_name: gitcall

require:
  postgresql_credentials: "main"
  rabbitmq_credentials: "main"

include:
  kube: d2721333 # main

helm:
  enabled: true
  app: gitcall
  tier: gitcall
  chart:
    version: "2.0.0"
    description: "The gitcall service. builds and runs usercode functions"

config_file: gitcall.json
<<<<<<< HEAD
image: "docker-hub.middleware.biz/gitcall/gitcall"
=======
image: "docker-hub.middleware.biz/public/gitcall/gitcall"
>>>>>>> 8a98885421f11256b3022593c35e3d2fc83820dd
