{{- define "cz.kubernetes.dockerconfig_secrets.v1" }}
{{- $root := . -}}
{{- range $_, $s := . }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .name | quote }}
  {{- if .labels }}
  labels:
  {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .annotations }}
  annotations:
  {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  .dockerconfigjson: {{ $s.config | mustToJson | b64enc }}
{{- end }}
{{- end }}