{{- define "cz.kubernetes.secrets.v1" }}
{{- $root := . }}
{{- range $_, $s := .}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | quote }}
  {{- if .labels }}
  labels:
  {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .annotations }}
  annotations:
  {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
stringData:
  {{- range $_, $data := $s.data }}
  {{ $data.key }}: {{ $data.value | quote }}
  {{- end }}
{{- end }}
{{- end }}