component_name: gitcall_migrations
helm:
  enabled: true
  app: gitcall
  tier: migrations
  chart:
    version: "0.1.1"
    description: "The gitcall migrations tool. It is run on deployment"
config_file: ""
image: hub-registry.svc.aku.com/public/gitcall/gitcall-migrations
