component_name: gitcall_docker_server

include:
  kube: d2721333 # main

helm:
  enabled: true
  app: gitcall
  tier: docker_server
  chart:
    version: "1.0.0"
    description: "The component for Docker Engine server"

config_file: daemon.json
<<<<<<< HEAD
image: "docker-hub.middleware.biz/library/docker"
=======
image: "docker-hub.middleware.biz/hub.docker.com/library/docker"
>>>>>>> 8a98885421f11256b3022593c35e3d2fc83820dd
image_version: "18.09.9-dind"
