{{- $d := .Values.helm }}
{{- range $_, $secret := $d.secrets}}
{{- if $secret.define }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name | quote }}
stringData:
{{- range $_, $data := $secret.data }}
  {{ $data.key }}: {{ $data.value | quote }}
---
{{- end }}
{{- end }}
{{- end }}