{{- $cfg := .Values.config }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitcall-pimp-service
  labels:
    release: {{ .Release.Name | quote }}
    app: {{ .Values.helm.app | quote }}
    tier: {{ .Values.helm.tier | quote }}
spec:
  selector:
    release: {{ .Release.Name | quote }}
    app: {{ .Values.helm.app | quote }}
    tier: {{ .Values.helm.tier | quote }}
    http: "true"
  ports:
  - protocol: TCP
    port: {{ $cfg.api.server.port }}
    targetPort: {{ $cfg.api.server.port }}
