apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-gitcall-pimp-service-account
  labels:
    release: {{ .Release.Name | quote }}
    app: {{ .Values.helm.app | quote }}
    tier: {{ .Values.helm.tier | quote }}
