{{- if .Values.global.capi.auth_providers_enable  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.capi.capi_saml_secret_name | default "capi-saml-secret" }}
  labels:
    app: {{ .Values.global.product }}
    tier: "capi"
type: Opaque
data:
{{- range $k, $v := $.Values.global.capi.saml_idp }}
  {{ $k }}_metadata.xml:
{{ toYaml $v.auth_metadata_content | b64enc | indent 4 }}
{{- end }}
{{- end }}
