---
apiVersion: v1
kind: Secret
metadata:
  name: license-share-new
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "license/corezoid_license" }}
  corezoid_license: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
