{{- if .Values.global.db.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.db.secret.name}}-root
  labels:
    app: {{ .Values.global.product }}
    tier: "postgres"
type: Opaque
data:
  dbsuperuser: {{ .Values.global.db.secret.dbsuperuser | b64enc | quote }}
  dbsuperuserpwd: {{ .Values.global.db.secret.dbsuperuserpwd | b64enc | quote }}
{{- end}}
