apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-main
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
  - name: syncapi-main
    protocol: TCP
    port: 8090
    targetPort: 8090
  type: NodePort
