{{- if eq .Values.global.enigma.enabled true }}
{{- if .Values.global.enigma.key_manager.aws_kms_role }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.enigma.key_manager.aws_kms_role }}
  name: enigma-kms-service
{{- end }}
  {{- end }}
