{{- if eq .Values.global.enigma.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
data:
      production.json: |
        {
            "name": "enigma-key-manager",
            "server": {
            "host": "0.0.0.0",
                "port": 8080
            },
            "logger": {
                "level": {{ .Values.global.log_level | default "info" }},
                "transports": [ "console" ],
                "path": "/tmp/"
            },
            "storage": {
                "database": "enigma",
                "ssl": false,
                "min": 2,
                "max": 5,
                "connectionTimeoutMillis": 5000,
                "idleTimeoutMillis": 5000
            },
            "kms": {
                "preferred": "amazon",
                "vault": {
                    "host": "enigma-vault-kms.service.consul",
                    "port": 8888
                },
                "amazon": {
                    "type": {{- if .Values.global.enigma.key_manager.aws_kms_role }} "env" {{- else }} "ec2" {{- end }}
                }
            }
        }
{{- end }}
