{{- if eq .Values.global.enigma.enabled true }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-autoscale
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  minReplicas: {{ .Values.global.enigma.key_manager.minReplicas }}
  maxReplicas: {{ .Values.global.enigma.key_manager.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  targetCPUUtilizationPercentage: 80
  {{- end }}
