apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-{{ .Release.Namespace }}
{{- if .Values.global.ingress.annotations }}
  annotations:
{{ toYaml .Values.global.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  rules:
    - host: {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /api/?/upload*
            backend:
              serviceName: mult-service-node
              servicePort: 9082
          - path: /api/?/copy*
            backend:
              serviceName: mult-service-node
              servicePort: 9082
          - path: /user_downloads*
            backend:
              serviceName: mult-service-node
              servicePort: 9082
          - path: /api/?/download*
            backend:
              serviceName: mult-service-node
              servicePort: 9082
          - path: /api/*
            backend:
              serviceName: capi-service-node
              servicePort: 9080
          - path: /auth/*
            backend:
              serviceName: capi-service-node
              servicePort: 9080
          - path: /system
            backend:
              serviceName: capi-service-node
              servicePort: 9080
          - backend:
              serviceName: corezoid-web-adm
              servicePort: 80

    - host: {{ .Values.global.web_superadm.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: corezoid-web-superadm
              servicePort: 80
    - host: {{ .Values.global.syncapi.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: syncapi-main
              servicePort: 8090
    {{- if .Values.global.merchant.enabled }}
    - host: {{ .Values.global.merchant.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: corezoid-web-adm
              servicePort: 80
    {{- end }}
    {{- if .Values.global.sa.enabled }}
    - host: {{ .Values.global.sa_web.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: single-account-web
              servicePort: 80
    {{- end }}
  {{- if .Values.global.ingress_tls }}
  tls:
    - hosts:
        - {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
        - {{ .Values.global.web_superadm.subdomain}}.{{ .Values.global.domain }}
        - {{ .Values.global.syncapi.subdomain}}.{{ .Values.global.domain }}
        {{- if .Values.global.sa.enabled }}
        - {{ .Values.global.sa_web.subdomain}}.{{ .Values.global.domain }}
        {{- end }}
        {{- if .Values.global.merchant.enabled }}
        - {{ .Values.global.merchant.subdomain}}.{{ .Values.global.domain }}
      {{- end }}
      secretName: tls-{{ .Values.appName }}-{{ .Release.Namespace }}
  {{- end }}
