{{- if  eq .Values.global.storage "manual" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-{{ .Values.global.storage}}-{{ .Release.Name }}
  labels:
    tier: {{ .Values.appName }}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /ebsmnt/{{ .Release.Name }}/{{ .Values.appName }}
{{- end }}
