apiVersion: v1
data:
  nginx.conf: |
    user  nginx;
    worker_processes 1;
    {{ $loglevel := .Values.global.log_level }}
    {{- if eq $loglevel "debug" }}
    error_log /dev/stdout debug;
    {{- else }}
    error_log /dev/stdout;
    {{- end }}
    pid        /var/run/nginx.pid;
    events {
        worker_connections  512000;
        multi_accept on;
    }

    http {

        server_names_hash_bucket_size 128;
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format main '$time_iso8601 $server_addr $server_port $request $status $body_bytes_sent $request_time $http_referer $http_user_agent $host';
        access_log /dev/stdout main;

        real_ip_header      X-Forwarded-For;
        set_real_ip_from    0.0.0.0/0;

        sendfile       on;
        tcp_nopush     on;

        server_tokens   off;
        proxy_buffering off;
        proxy_max_temp_file_size 0;
        keepalive_timeout  65;
        gzip on;
        gzip_types text/css application/x-javascript text/xml application/xml application/xml+rss text/plain application/javascript text/javascript application/json image/png image/svg+xml;
        gzip_proxied any;
        include /etc/nginx/conf.d/*.conf;
    }

kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-main
