apiVersion: v1
data:
  corezoid.conf: |
    map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
    }
    server {
        listen 80;
        server_name localhost;
    	root /usr/share/nginx/html;

        location = /ping { return 200; break; }
        location = /nginx_status { stub_status; }
    }

    server {
        listen 80;
        server_name {{ .Values.global.subdomain}}.{{ .Values.global.domain }};

        add_header "Cache-Control" "no-store";
        add_header "Pragma" "no-cache";

        add_header X-Frame-Options SAMEORIGIN;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
        proxy_cookie_path / "/; HTTPOnly; Secure";

        add_header Feature-Policy "geolocation 'none'; camera 'none';";
        add_header 'Referrer-Policy' 'origin-when-cross-origin';

        add_header Content-Security-Policy "default-src 'self' https://*.gravatar.com https://*.gstatic.com https://www.google.com https://www.google-analytics.com https://*.{{ .Values.global.subdomain}}.{{ .Values.global.domain }}  'unsafe-inline'; frame-src 'self' https://*.gravatar.com https://*.google.com https://*.{{ .Values.global.subdomain}}.{{ .Values.global.domain }}; script-src 'self' https://*.{{ .Values.global.subdomain}}.{{ .Values.global.domain }} https://*.gravatar.com https://*.gstatic.com https://www.google.com https://www.googletagmanager.com https://ajax.googleapis.com https://www.google-analytics.com 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://www.google-analytics.com https://stats.g.doubleclick.net wss://*.{{ .Values.global.subdomain}}.{{ .Values.global.domain }}; img-src 'self' https://*.gravatar.com https://www.google.com https://www.google.com.ua https://*.{{ .Values.global.subdomain}}.{{ .Values.global.domain }} https://www.google-analytics.com  https://*.gstatic.com data:; object-src 'self'; font-src 'self' https://*.gravatar.com https://*.gstatic.com https://www.google.com https://fonts.gstatic.com https://fonts.googleapis.com data:; style-src * blob: 'self' https://*.gravatar.com https://*.gstatic.com https://www.google.com https://*.{{ .Values.global.subdomain}}.{{ .Values.global.domain }} https://fonts.gstatic.com https://fonts.googleapis.com 'unsafe-inline';";


        large_client_header_buffers     4 16k;
        client_body_buffer_size 16k;
        client_max_body_size 16m;

        set $static_root    "/usr/share/nginx/html/capi-js";
        set $admin_root    "/usr/share/nginx/html";
        set $static_local    "/usr/share/nginx/html/static";


        if ($host !~* ^({{ .Values.global.subdomain}}.{{ .Values.global.domain }})$ ) { return 444; }

        location ~ ^/avatars { return 200; }

        location /favicon/ {
           root /usr/share/nginx/html;
           add_header X-Content-Type-Options "nosniff";
        }

        location /logo/ { root /usr/share/nginx/html; }

        location = /favicon.ico { return 200; 	add_header X-Content-Type-Options "nosniff"; }

        location / {
            root $admin_root;
            try_files $uri /index.html;
            expires 1y;
            add_header Cache-Control "public";
        }

        location ~ ^/editor {
            root $admin_root;
            try_files $uri /editor.html;
            expires 1y;
            add_header Cache-Control "public";
        }

        location ~ ^(/[a-zA-Z0-9]+)?/dashboard {
            root $admin_root;
            try_files $uri /dashboard.html;
            expires 1y;
            add_header Cache-Control "public";
        }

        location ~ ^(/[a-zA-Z0-9]+)?/process {
            root $admin_root;
            try_files $uri /editor.html;
            expires 1y;
            add_header Cache-Control "public";
        }

        location ~ ^/api/[0-9]/sock_json {
            proxy_pass http://capi-service:9080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_intercept_errors on;
        }

        location ~ ^/api/[0-9]/json {
            add_header X-Content-Type-Options "nosniff";
            add_header X-Frame-Options "SAMEORIGIN";
            proxy_pass http://capi-service:9080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_intercept_errors on;
            proxy_read_timeout        300;
            proxy_send_timeout        300;
        }

        location ~ ^/api/[0-9]/xml {
            add_header X-Content-Type-Options "nosniff";
            proxy_pass http://capi-service:9080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_intercept_errors on;
            proxy_read_timeout        300;
            proxy_send_timeout        300;
        }

        location ~ ^/api/[0-9]/nvp {
            add_header X-Content-Type-Options "nosniff";
            proxy_pass http://capi-service:9080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_intercept_errors on;
            proxy_read_timeout        300;
            proxy_send_timeout        300;
        }

        location ~ ^/api/[0-9]/plugins {
            add_header X-Content-Type-Options "nosniff";
            proxy_pass http://capi-service:9080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_intercept_errors on;
            proxy_read_timeout        300;
            proxy_send_timeout        300;
        }

        location ~ ^/api/2/(download|upload|copy) {
            add_header X-Content-Type-Options "nosniff";
            proxy_pass http://mult-service:9082;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_buffering off;
            proxy_intercept_errors on;
        }

        location /user_downloads {
            add_header X-Content-Type-Options "nosniff";
            proxy_pass http://mult-service:9082;
            proxy_set_header   Host           $host;
            proxy_set_header X-Forwarded-For  $remote_addr;
            proxy_buffering off;
            proxy_intercept_errors on;
            proxy_read_timeout        300;
            proxy_send_timeout        300;
        }

        location /support { return 301 https://{{ .Values.global.subdomain}}.{{ .Values.global.domain }}/auth2/saml/support; }

        location /auth {
            add_header X-Content-Type-Options "nosniff";
            proxy_set_header   Host           $host;
            proxy_set_header X-Forwarded-For  $remote_addr;
            proxy_buffering off;
            proxy_pass http://capi-service:9080;
        }

        location /system {
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
            #add_header X-Content-Type-Options "text/html";
            add_header X-Content-Type-Options "nosniff";
            proxy_set_header   Host           $host;
            proxy_set_header X-Forwarded-For  $remote_addr;
            proxy_buffering off;
            proxy_pass http://capi-service:9080;
            proxy_connect_timeout     360;
            proxy_read_timeout        360;
            proxy_send_timeout        720;
        }

        location ~ ^/multitenant/(js|css) {
            root /usr/share/nginx/html/multitenant;
            expires 1M;
            add_header Cache-Control "public";
        }

        location ~ ^/multitenant {
            root /usr/share/nginx/html/multitenant;
            rewrite / /index.html break;
            try_files $uri /index.html;
            expires 1M;
            add_header Cache-Control "public";
        }

        location /superadmin {
        rewrite ^/superadmin(.*)$ https://{{ .Values.global.web_superadm.subdomain}}.{{ .Values.global.domain }} redirect;
        }

    }

kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-site
