{{- if .Values.global.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}-policy
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  podSelector:
    matchLabels:
      tier: {{ .Values.appName }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{ .Values.global.networkPolicy.labelsSelector.ingress.namespaceSelector | toYaml}}
        - podSelector:
            matchLabels:
              {{ .Values.global.networkPolicy.labelsSelector.ingress.podSelector | toYaml }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{ .Values.global.networkPolicy.labelsSelector.monitoring.namespaceSelector | toYaml }}
        - podSelector:
            matchLabels:
              {{ .Values.global.networkPolicy.labelsSelector.ingress.podSelector | toYaml }}
{{- end}}
