apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
