apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-merchant
data:
  merchant.conf: |
    server {
        listen 80;
        server_name {{ .Values.global.merchant.subdomain}}.{{ .Values.global.domain }};
        add_header Strict-Transport-Security max-age=15768000;
        proxy_intercept_errors on;
        underscores_in_headers on;

    location / {
      proxy_pass http://merchant-service:8080;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   Host $http_host;
      proxy_pass_header  GMT_UNIXTIME;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass_header  SIGNATURE;
      proxy_pass_header  API_LOGIN;
      }
    }


