apiVersion: v1
data:
  superadm.conf: |
    server {
        listen       80;
        server_name  superadm-{{ .Values.global.subdomain}}.{{ .Values.global.domain }};

        location / {
    	    root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        add_header "Cache-Control" "no-store";
        add_header "Pragma" "no-cache";

        add_header X-Frame-Options SAMEORIGIN;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
        proxy_cookie_path / "/; HTTPOnly; Secure";

        large_client_header_buffers     4 16k;
        client_body_buffer_size 16k;
        client_max_body_size 16m;


        location /f {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }


        location /api {
            proxy_pass http://conf-agent-server-service:8585;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;

        }

        location /auth {
            proxy_pass http://capi-service:9080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;

        }

        location /system {
            proxy_pass http://capi-service:9080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;

        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-site
