apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-autoscale
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  targetCPUUtilizationPercentage: 80
