{{- if ( .Values.global.elasticsearch.internal )}}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.product }}
        tier: {{ .Values.appName }}
    spec:
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: {{ .Values.appName }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.global.repotype | default "public" }}{{ .Values.image.repository }}:{{ .Values.global.elasticsearch.tag }}"
          env:
            - name: ES_JAVA_OPTS
              value: "-Xmx1g -Xms1g"
          ports:
            - name: es
              protocol: TCP
              containerPort: 9200
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 90
       {{- if not  (eq .Values.global.repotype "public") }}
      imagePullSecrets:
        - name: corezoid-secret
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.elasticsearch.secret.data.host }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200


{{- end }}
